[package]
name = "binance_0001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance = "0.20.2"
chrono = "0.4.26"
serde_json = "1.0.104"
simple_excel_writer = "0.2.0"
